# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15bea4e793dd4d67ef81ee651de364f3cce5e49dc5fa1e5e2537c44324dcf194f1d9e8fddbf6a5c658974549a0862b85586c733aaec850dbb9633269e885f770

test:
  secret_key_base: 24345a1cbb4a99114e57e1850f4555299ab40064654d2578bf0f24a7818077751ba6ec03414cbe5738b8b8ee95ff88248c6efdc5d7feec60b7811ac5a8b96548

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
